package OrgTests;

import static org.assertj.core.api.Assertions.assertThat;

import Config.DeploymentLevel;
import Database.Organization.OrgDao;
import Database.Organization.OrgDaoFactory;
import Database.User.UserDao;
import Database.User.UserDaoFactory;
import TestUtils.TestUtils;
import java.util.UUID;
import kong.unirest.HttpResponse;
import kong.unirest.Unirest;
import org.json.JSONObject;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class NewOrgTest {
  private static UserDao userDao;
  private static OrgDao orgDao;

  @BeforeClass
  public static void setUp() {
    TestUtils.startServer();
    userDao = UserDaoFactory.create(DeploymentLevel.TEST);
    orgDao = OrgDaoFactory.create(DeploymentLevel.TEST);
    userDao.clear();
    orgDao.clear();
  }

  @AfterClass
  public static void tearDown() {
    userDao.clear();
    orgDao.clear();
  }

  @Test
  public void testNewOrgSignupWithAutoGeneratedUsername() {
    String uniqueSuffix = UUID.randomUUID().toString().replace("-", "").substring(0, 8);
    String orgName = "SignupOrg" + uniqueSuffix;

    JSONObject body = new JSONObject();
    body.put("firstname", "Cat");
    body.put("lastname", "Chen");
    body.put("birthDate", "05-23-2002");
    body.put("email", "");
    body.put("phonenumber", "");
    body.put("address", "");
    body.put("city", "");
    body.put("state", "");
    body.put("zipcode", "");
    body.put("twoFactorOn", false);
    body.put("username", "");
    body.put("password", "password123");
    body.put("organizationName", orgName);
    body.put("organizationWebsite", "https://keep.id");
    body.put("organizationEIN", "123456789");
    body.put("organizationAddressStreet", "321 RandomStreet");
    body.put("organizationAddressCity", "Philadelphia");
    body.put("organizationAddressState", "PA");
    body.put("organizationAddressZipcode", "19104");
    body.put("organizationEmail", "test" + uniqueSuffix + "@email.com");
    body.put("organizationPhoneNumber", "4121233456");

    HttpResponse<String> submitResponse =
        Unirest.post(TestUtils.getServerUrl() + "/organization-signup")
            .header("Accept", "*/*")
            .header("Content-Type", "text/plain")
            .body(body.toString())
            .asString();

    JSONObject responseJSON = TestUtils.responseStringToJSON(submitResponse.getBody());
    assertThat(responseJSON.getString("status")).isEqualTo("SUCCESSFUL_ENROLLMENT");
    assertThat(orgDao.get(orgName)).isPresent();
  }
}
